#pragma once

#include "../../core/vertex.hpp"
#include "i_graphics_service.hpp"
#include <array>
#include <cstdint>
#include <filesystem>
#include <string>
#include <unordered_map>
#include <vector>

namespace sdl3cpp::services {

/**
 * @brief Scene object data structure.
 */
struct SceneObject {
    std::string id;
    std::vector<core::Vertex> vertices;
    std::vector<uint16_t> indices;
    std::string shaderKey;
    int modelMatrixFuncRef;  // Lua function reference
};

/**
 * @brief GUI input snapshot for Lua.
 */
struct GuiInputSnapshot {
    float mouseX;
    float mouseY;
    float mouseWheelDelta;
    bool mouseLeftPressed;
    bool mouseRightPressed;
    std::string textInput;
};

// Forward declare GUI types (defined in script/gui_types.hpp)
struct GuiCommand;

/**
 * @brief Script service interface (Lua integration).
 *
 * Provides a clean API for Lua script execution and data exchange.
 * Wraps the ScriptEngine and its internal managers (SceneManager,
 * ShaderManager, GuiManager, AudioManager).
 */
class IScriptService {
public:
    virtual ~IScriptService() = default;

    /**
     * @brief Load and execute a Lua script.
     *
     * @param path Path to the Lua script file
     * @param debug Whether to enable Lua debug mode
     * @throws std::runtime_error if script loading fails
     */
    virtual void LoadScript(const std::filesystem::path& path, bool debug) = 0;

    /**
     * @brief Load scene objects from Lua.
     *
     * Calls the Lua function that generates the scene graph.
     *
     * @return Vector of scene objects with geometry and metadata
     */
    virtual std::vector<SceneObject> LoadSceneObjects() = 0;

    /**
     * @brief Compute model matrix for an object using Lua function.
     *
     * @param funcRef Lua function reference (from SceneObject)
     * @param time Current time in seconds
     * @return 4x4 model transformation matrix (column-major)
     */
    virtual std::array<float, 16> ComputeModelMatrix(int funcRef, float time) = 0;

    /**
     * @brief Get view-projection matrix from Lua.
     *
     * @param aspect Window aspect ratio (width/height)
     * @return 4x4 view-projection matrix (column-major)
     */
    virtual std::array<float, 16> GetViewProjectionMatrix(float aspect) = 0;

    /**
     * @brief Load shader paths from Lua configuration.
     *
     * @return Map of shader key to shader file paths
     */
    virtual std::unordered_map<std::string, ShaderPaths> LoadShaderPaths() = 0;

    /**
     * @brief Update GUI input state in Lua.
     *
     * Sends current input state to Lua for GUI processing.
     *
     * @param input Input snapshot for this frame
     */
    virtual void UpdateGuiInput(const GuiInputSnapshot& input) = 0;

    /**
     * @brief Get GUI rendering commands from Lua.
     *
     * Retrieves the list of GUI commands generated by Lua scripts.
     *
     * @return Vector of GUI commands to render
     */
    virtual std::vector<GuiCommand> GetGuiCommands() = 0;

    /**
     * @brief Check if there are pending GUI commands.
     *
     * @return true if GUI commands are available, false otherwise
     */
    virtual bool HasGuiCommands() const = 0;

    /**
     * @brief Update physics simulation (calls Lua if needed).
     *
     * @param deltaTime Time since last update in seconds
     */
    virtual void UpdatePhysics(float deltaTime) = 0;
};

}  // namespace sdl3cpp::services
